### ISSUE TITLE
Clear button closes the date range picker

### ISSUE THREAD

**Issue by snpower** [tamble/jquery-ui-daterangepicker#48]
First off, great widget - just what I've been looking for!

However, from a UX perspective, it would be better if the "Clear" button didn't close the date range picker widget. It should just call clearRange() and not close() as well.

Stella

**Comment by op16** [comment]
The "Clear" button was introduced because we use the widget as a filter, and we needed to allow the user to return the widget to a no-value state (pass-all).

A new user might think it's required to push the "Clear" button before selecting a new range, in which case the closing of the dropdown would be unexpected and inconvenient. However using the button is not required in that case, and the user can simply select a new range.

If the user is required to pick a date range you would better not display the "Clear" button at all (by setting an empty `clearButtonText`) and eliminate the possibility for such confusion.

**Comment by op16** [comment]
If you actually need to use the "Clear" button, reopen this issue and we will implement a new option, closeOnClear: true
