### ISSUE TITLE
Unable to select range when using beforeShowDay

### ISSUE THREAD

**Issue by digitalredefned** [tamble/jquery-ui-daterangepicker#9]
I've got an example at http://git.digitalredefined.com/ that is using the plugin and to disablel unavailable days, I'm using a function called by beforeShowDay.  When I don't use the method, I am able to select a date range.  But, when I use the method I can only select a single day.  No errors in console and method working as designed.  Any help/thoughts appreciated.

Jim

**Comment by op16** [comment]
That is due to a bug in our code. We use the beforeShowDay function for the range selection, but try to take into account the one passed as a param be users.

But the resulting class name is missing a space in the concat:
<code>result[1] + userResult[1]</code>

I'll release a fix later. Thanks for your report.

**Comment by digitalredefned** [comment]
Works great, thanks!
